export const FAKE_POPULARS = [
  {
    adult: false,
    backdrop_path: "/hH4YaZuH89Hlyz0DEkf362Mj8gU.jpg",
    genre_ids: [35],
    id: 65701,
    origin_country: ["US"],
    original_language: "en",
    original_name: "Good Mythical Morning",
    overview:
      'Two "Internetainers" (Rhett & Link) go far out and do the weirdest  things, giving you a daily dose of casual comedy every Monday-Friday.',
    popularity: 3283.388,
    poster_path: "/2Fja87aTeuXxTEI1MH2IuHHSsLq.jpg",
    first_air_date: "2012-01-09",
    name: "Good Mythical Morning",
    vote_average: 7.045,
    vote_count: 44,
  },
];

export const FAKE_RECOMMENDATIONS = [
  {
    adult: false,
    backdrop_path: "/2yDV0xLyqW88dn5qE7YCRnoYmfy.jpg",
    id: 4613,
    name: "Band of Brothers",
    original_language: "en",
    original_name: "Band of Brothers",
    overview:
      "Drawn from interviews with survivors of Easy Company, as well as their journals and letters, Band of Brothers chronicles the experiences of these men from paratrooper training in Georgia through the end of the war. As an elite rifle company parachuting into Normandy early on D-Day morning, participants in the Battle of the Bulge, and witness to the horrors of war, the men of Easy knew extraordinary bravery and extraordinary fear - and became the stuff of legend. Based on Stephen E. Ambrose's acclaimed book of the same name.",
    poster_path: "/bV7RYiz6YiSfLYynRWNTFdcgEM1.jpg",
    media_type: "tv",
    genre_ids: [18, 10768],
    popularity: 113.944,
    first_air_date: "2001-09-09",
    vote_average: 8.511,
    vote_count: 3281,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/1F2RnXLc0fmRt7iWfBK4mNVsjno.jpg",
    id: 34524,
    name: "Teen Wolf",
    original_language: "en",
    original_name: "Teen Wolf",
    overview:
      "Scott McCall, a high school student living in the town of Beacon Hills has his life drastically changed when he's bitten by a werewolf, becoming one himself. He must henceforth learn to balance his problematic new identity with his day-to-day teenage life. The following characters are instrumental to his struggle: Stiles, his best friend; Allison, his love interest who comes from a family of werewolf hunters; and Derek, a mysterious werewolf with a dark past. Throughout the series, he strives to keep his loved ones safe while maintaining normal relationships with them.",
    poster_path: "/fmlMmxSBgPEunHS5gjokIej048g.jpg",
    media_type: "tv",
    genre_ids: [10765, 18, 35],
    popularity: 253.177,
    first_air_date: "2011-06-05",
    vote_average: 8.54,
    vote_count: 3974,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/vcFW09U4834DyFOeRZpsx9x1D3S.jpg",
    id: 57243,
    name: "Doctor Who",
    original_language: "en",
    original_name: "Doctor Who",
    overview:
      "The Doctor is a Time Lord: a 900 year old alien with 2 hearts, part of a gifted civilization who mastered time travel. The Doctor saves planets for a living—more of a hobby actually, and the Doctor's very, very good at it.",
    poster_path: "/4edFyasCrkH4MKs6H4mHqlrxA6b.jpg",
    media_type: "tv",
    genre_ids: [10759, 18, 10765],
    popularity: 801.448,
    first_air_date: "2005-03-26",
    vote_average: 7.491,
    vote_count: 2812,
    origin_country: ["GB"],
  },
  {
    adult: false,
    backdrop_path: "/Aj3hb13leEgC4lmU4YwRC4NaBsk.jpg",
    id: 4556,
    name: "Scrubs",
    original_language: "en",
    original_name: "Scrubs",
    overview:
      'In the unreal world of Sacred Heart Hospital, John "J.D." Dorian learns the ways of medicine, friendship and life.',
    poster_path: "/brJUMAL90m8WSpo9A86S9wZuox6.jpg",
    media_type: "tv",
    genre_ids: [35],
    popularity: 345.04,
    first_air_date: "2001-10-02",
    vote_average: 8.022,
    vote_count: 1656,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/bp6RoEQMX3lfuZOIPw7Su5c5WCP.jpg",
    id: 387,
    name: "SpongeBob SquarePants",
    original_language: "en",
    original_name: "SpongeBob SquarePants",
    overview:
      "Deep down in the Pacific Ocean in the subterranean city of Bikini Bottom lives a square yellow sponge named SpongeBob SquarePants. SpongeBob lives in a pineapple with his pet snail, Gary, loves his job as a fry cook at the Krusty Krab, and has a knack for getting into all kinds of trouble without really trying. When he's not getting on the nerves of his cranky next door neighbor Squidward, SpongeBob can usually be found smack in the middle of all sorts of strange situations with his best buddy, the simple yet lovable starfish, Patrick, or his thrill-seeking surfer-girl squirrel pal, Sandy Cheeks.",
    poster_path: "/zDuKxQkG8EemvLdBn43ChdM0MJL.jpg",
    media_type: "tv",
    genre_ids: [16, 35, 10751, 10765],
    popularity: 64.523,
    first_air_date: "1999-05-01",
    vote_average: 7.621,
    vote_count: 2828,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/mmprryb2r0X8u9JkZCnaJIzyYX4.jpg",
    id: 62688,
    name: "Supergirl",
    original_language: "en",
    original_name: "Supergirl",
    overview:
      "Twenty-four-year-old Kara Zor-El, who was taken in by the Danvers family when she was 13 after being sent away from Krypton, must learn to embrace her powers after previously hiding them. The Danvers teach her to be careful with her powers, until she has to reveal them during an unexpected disaster, setting her on her journey of heroism.",
    poster_path: "/cFO65xb0xiXKqk5BmgHawCXB1i0.jpg",
    media_type: "tv",
    genre_ids: [18, 10765, 10759],
    popularity: 185.767,
    first_air_date: "2015-10-26",
    vote_average: 7.332,
    vote_count: 4063,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/tZmlWeFEMvxrjJhBJJcLNXpSRiG.jpg",
    id: 66573,
    name: "The Good Place",
    original_language: "en",
    original_name: "The Good Place",
    overview:
      "Eleanor Shellstrop, an ordinary woman who, through an extraordinary string of events, enters the afterlife where she comes to realize that she hasn't been a very good person. With the help of her wise afterlife mentor, she's determined to shed her old way of living and discover the awesome (or at least the pretty good) person within.",
    poster_path: "/qIhsuhoIYR5yTnDta0IL4senbeN.jpg",
    media_type: "tv",
    genre_ids: [10765, 35],
    popularity: 83.814,
    first_air_date: "2016-09-19",
    vote_average: 8,
    vote_count: 1421,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/soQgquPkLmUu9eKLJJzuA4KZDyi.jpg",
    id: 69050,
    name: "Riverdale",
    original_language: "en",
    original_name: "Riverdale",
    overview:
      "Set in the present, the series offers a bold, subversive take on Archie, Betty, Veronica and their friends, exploring the surreality of small-town life, the darkness and weirdness bubbling beneath Riverdale’s wholesome facade.",
    poster_path: "/c1ROxK1Afo6YuGi3j6ClXmrNcHi.jpg",
    media_type: "tv",
    genre_ids: [80, 18, 9648],
    popularity: 360.49,
    first_air_date: "2017-01-26",
    vote_average: 8.464,
    vote_count: 13281,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/rEjhgSvSPlsQOkmYXNzairEvXWB.jpg",
    id: 62823,
    name: "Scream: The TV Series",
    original_language: "en",
    original_name: "Scream: The TV Series",
    overview:
      "What starts as a YouTube video going viral, soon leads to problems for the teenagers of Lakewood and serves as the catalyst for a murder that opens up a window to the town's troubled past. Everyone has secrets. Everyone tells lies. Everyone is fair game.",
    poster_path: "/cTRUcUnAydqboYfis0IhhY1edDt.jpg",
    media_type: "tv",
    genre_ids: [18, 80, 9648],
    popularity: 71.388,
    first_air_date: "2015-06-30",
    vote_average: 6.883,
    vote_count: 1068,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/qsnXwGS7KBbX4JLqHvICngtR8qg.jpg",
    id: 61889,
    name: "Marvel's Daredevil",
    original_language: "en",
    original_name: "Marvel's Daredevil",
    overview:
      "Lawyer-by-day Matt Murdock uses his heightened senses from being blinded as a young boy to fight crime at night on the streets of Hell’s Kitchen as Daredevil.",
    poster_path: "/QWbPaDxiB6LW2LjASknzYBvjMj.jpg",
    media_type: "tv",
    genre_ids: [80, 18, 10759],
    popularity: 169.155,
    first_air_date: "2015-04-10",
    vote_average: 8.167,
    vote_count: 4220,
    origin_country: ["US"],
  },
];
